project:
  type: website
  output-dir: docs

website:
  title: "Emma Pingel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project1.qmd
        text: CO Streamflow Analysis 
      - href: project2.qmd
        text: IA Embodied Emissions

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

